Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Friend Class libsoxPINVOKE

        Protected Class SWIGExceptionHelper_t

            Public Delegate Sub ExceptionDelegate(ByVal message As String)
            Public Delegate Sub ExceptionArgumentDelegate(ByVal message As String, ByVal paramName As String)

            Private Shared applicationDelegate As New ExceptionDelegate(AddressOf SetPendingApplicationException)
            Private Shared arithmeticDelegate As New ExceptionDelegate(AddressOf SetPendingArithmeticException)
            Private Shared divideByZeroDelegate As New ExceptionDelegate(AddressOf SetPendingDivideByZeroException)
            Private Shared indexOutOfRangeDelegate As New ExceptionDelegate(AddressOf SetPendingIndexOutOfRangeException)
            Private Shared invalidCastDelegate As New ExceptionDelegate(AddressOf SetPendingInvalidCastException)
            Private Shared invalidOperationDelegate As New ExceptionDelegate(AddressOf SetPendingInvalidOperationException)
            Private Shared ioDelegate As New ExceptionDelegate(AddressOf SetPendingIOException)
            Private Shared nullReferenceDelegate As New ExceptionDelegate(AddressOf SetPendingNullReferenceException)
            Private Shared outOfMemoryDelegate As New ExceptionDelegate(AddressOf SetPendingOutOfMemoryException)
            Private Shared overflowDelegate As New ExceptionDelegate(AddressOf SetPendingOverflowException)
            Private Shared systemDelegate As New ExceptionDelegate(AddressOf SetPendingSystemException)

            Private Shared argumentDelegate As New ExceptionArgumentDelegate(AddressOf SetPendingArgumentException)
            Private Shared argumentNullDelegate As New ExceptionArgumentDelegate(AddressOf SetPendingArgumentNullException)
            Private Shared argumentOutOfRangeDelegate As New ExceptionArgumentDelegate(AddressOf SetPendingArgumentOutOfRangeException)

            <DllImport("libsox", EntryPoint:="SWIGRegisterExceptionCallbacks_libsox")>
            Public Shared Sub SWIGRegisterExceptionCallbacks_libsox(ByVal applicationDelegate As ExceptionDelegate, ByVal arithmeticDelegate As ExceptionDelegate, ByVal divideByZeroDelegate As ExceptionDelegate, ByVal indexOutOfRangeDelegate As ExceptionDelegate, ByVal invalidCastDelegate As ExceptionDelegate, ByVal invalidOperationDelegate As ExceptionDelegate, ByVal ioDelegate As ExceptionDelegate, ByVal nullReferenceDelegate As ExceptionDelegate, ByVal outOfMemoryDelegate As ExceptionDelegate, ByVal overflowDelegate As ExceptionDelegate, ByVal systemExceptionDelegate As ExceptionDelegate)
            End Sub

            <DllImport("libsox", EntryPoint:="SWIGRegisterExceptionArgumentCallbacks_libsox")>
            Public Shared Sub SWIGRegisterExceptionCallbacksArgument_libsox(ByVal argumentDelegate As ExceptionArgumentDelegate, ByVal argumentNullDelegate As ExceptionArgumentDelegate, ByVal argumentOutOfRangeDelegate As ExceptionArgumentDelegate)
            End Sub

            Private Shared Sub SetPendingApplicationException(ByVal message As String)
                SWIGPendingException.Set(New ApplicationException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingArithmeticException(ByVal message As String)
                SWIGPendingException.Set(New ArithmeticException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingDivideByZeroException(ByVal message As String)
                SWIGPendingException.Set(New DivideByZeroException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingIndexOutOfRangeException(ByVal message As String)
                SWIGPendingException.Set(New IndexOutOfRangeException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingInvalidCastException(ByVal message As String)
                SWIGPendingException.Set(New InvalidCastException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingInvalidOperationException(ByVal message As String)
                SWIGPendingException.Set(New InvalidOperationException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingIOException(ByVal message As String)
                SWIGPendingException.Set(New System.IO.IOException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingNullReferenceException(ByVal message As String)
                SWIGPendingException.Set(New NullReferenceException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingOutOfMemoryException(ByVal message As String)
                SWIGPendingException.Set(New OutOfMemoryException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingOverflowException(ByVal message As String)
                SWIGPendingException.Set(New OverflowException(message, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingSystemException(ByVal message As String)
                SWIGPendingException.Set(New SystemException(message, SWIGPendingException.Retrieve()))
            End Sub

            Private Shared Sub SetPendingArgumentException(ByVal message As String, ByVal paramName As String)
                SWIGPendingException.Set(New ArgumentException(message, paramName, SWIGPendingException.Retrieve()))
            End Sub
            Private Shared Sub SetPendingArgumentNullException(ByVal message As String, ByVal paramName As String)
                Dim e As Exception = SWIGPendingException.Retrieve()
                If e IsNot Nothing Then
                    message = message & " Inner Exception: " & e.Message
                End If
                SWIGPendingException.Set(New ArgumentNullException(paramName, message))
            End Sub
            Private Shared Sub SetPendingArgumentOutOfRangeException(ByVal message As String, ByVal paramName As String)
                Dim e As Exception = SWIGPendingException.Retrieve()
                If e IsNot Nothing Then
                    message = message & " Inner Exception: " & e.Message
                End If
                SWIGPendingException.Set(New ArgumentOutOfRangeException(paramName, message))
            End Sub

            Shared Sub New()
                SWIGRegisterExceptionCallbacks_libsox(applicationDelegate, arithmeticDelegate, divideByZeroDelegate, indexOutOfRangeDelegate, invalidCastDelegate, invalidOperationDelegate, ioDelegate, nullReferenceDelegate, outOfMemoryDelegate, overflowDelegate, systemDelegate)

                SWIGRegisterExceptionCallbacksArgument_libsox(argumentDelegate, argumentNullDelegate, argumentOutOfRangeDelegate)
            End Sub
        End Class

        Protected Shared swigExceptionHelper As New SWIGExceptionHelper_t

        Public Class SWIGPendingException
            <ThreadStatic()>
            Private Shared pendingException As Exception = Nothing
            Private Shared numExceptionsPending As Integer = 0

            Public Shared ReadOnly Property Pending() As Boolean
                Get
                    'INSTANT VB NOTE: The local variable pending was renamed since Visual Basic will not allow local variables with the same name as their enclosing function or property:
                    Dim pending_Renamed As Boolean = False
                    If numExceptionsPending > 0 Then
                        If pendingException IsNot Nothing Then
                            pending_Renamed = True
                        End If
                    End If
                    Return pending_Renamed
                End Get
            End Property

            Public Shared Sub [Set](ByVal e As Exception)
                If pendingException IsNot Nothing Then
                    Throw New ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" & pendingException.ToString() & ")", e)
                End If
                pendingException = e
                SyncLock GetType(libsoxPINVOKE)
                    numExceptionsPending += 1
                End SyncLock
            End Sub

            Public Shared Function Retrieve() As Exception
                Dim e As Exception = Nothing
                If numExceptionsPending > 0 Then
                    If pendingException IsNot Nothing Then
                        e = pendingException
                        pendingException = Nothing
                        SyncLock GetType(libsoxPINVOKE)
                            numExceptionsPending -= 1
                        End SyncLock
                    End If
                End If
                Return e
            End Function
        End Class


        Protected Class SWIGStringHelper_t

            Public Delegate Function SWIGStringDelegate(ByVal message As String) As String
            Private Shared stringDelegate As New SWIGStringDelegate(AddressOf CreateString)

            <DllImport("libsox", EntryPoint:="SWIGRegisterStringCallback_libsox")>
            Public Shared Sub SWIGRegisterStringCallback_libsox(ByVal stringDelegate As SWIGStringDelegate)
            End Sub

            Private Shared Function CreateString(ByVal cString As String) As String
                Return cString
            End Function

            Shared Sub New()
                SWIGRegisterStringCallback_libsox(stringDelegate)
            End Sub
        End Class

        Protected Shared SWIGStringHelper As New SWIGStringHelper_t


        Shared Sub New()
        End Sub


        <DllImport("libsox", EntryPoint:="CSharp_CHAR_BIT_get")>
        Public Shared Function CHAR_BIT_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SCHAR_MIN_get")>
        Public Shared Function SCHAR_MIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SCHAR_MAX_get")>
        Public Shared Function SCHAR_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_UCHAR_MAX_get")>
        Public Shared Function UCHAR_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_CHAR_MIN_get")>
        Public Shared Function CHAR_MIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_CHAR_MAX_get")>
        Public Shared Function CHAR_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_MB_LEN_MAX_get")>
        Public Shared Function MB_LEN_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SHRT_MIN_get")>
        Public Shared Function SHRT_MIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SHRT_MAX_get")>
        Public Shared Function SHRT_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_USHRT_MAX_get")>
        Public Shared Function USHRT_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_INT_MIN_get")>
        Public Shared Function INT_MIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_INT_MAX_get")>
        Public Shared Function INT_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_UINT_MAX_get")>
        Public Shared Function UINT_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_LONG_MIN_get")>
        Public Shared Function LONG_MIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_LONG_MAX_get")>
        Public Shared Function LONG_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_ULONG_MAX_get")>
        Public Shared Function ULONG_MAX_get() As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SIZE_MAX_get")>
        Public Shared Function SIZE_MAX_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_int8_size_get")>
        Public Shared Function lsx_static_assert_sox_int8_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_uint8_size_get")>
        Public Shared Function lsx_static_assert_sox_uint8_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_int16_size_get")>
        Public Shared Function lsx_static_assert_sox_int16_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_uint16_size_get")>
        Public Shared Function lsx_static_assert_sox_uint16_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_int32_size_get")>
        Public Shared Function lsx_static_assert_sox_int32_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_uint32_size_get")>
        Public Shared Function lsx_static_assert_sox_uint32_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_int64_size_get")>
        Public Shared Function lsx_static_assert_sox_int64_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_static_assert_sox_uint64_size_get")>
        Public Shared Function lsx_static_assert_sox_uint64_size_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_LIB_VERSION_CODE_get")>
        Public Shared Function SOX_LIB_VERSION_CODE_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_SAMPLE_PRECISION_get")>
        Public Shared Function SOX_SAMPLE_PRECISION_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_SAMPLE_NEG_get")>
        Public Shared Function SOX_SAMPLE_NEG_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_UNSPEC_get")>
        Public Shared Function SOX_UNSPEC_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_DEFAULT_CHANNELS_get")>
        Public Shared Function SOX_DEFAULT_CHANNELS_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_DEFAULT_RATE_get")>
        Public Shared Function SOX_DEFAULT_RATE_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_DEFAULT_PRECISION_get")>
        Public Shared Function SOX_DEFAULT_PRECISION_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_MAX_NLOOPS_get")>
        Public Shared Function SOX_MAX_NLOOPS_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_NOSTDIO_get")>
        Public Shared Function SOX_FILE_NOSTDIO_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_DEVICE_get")>
        Public Shared Function SOX_FILE_DEVICE_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_PHONY_get")>
        Public Shared Function SOX_FILE_PHONY_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_REWIND_get")>
        Public Shared Function SOX_FILE_REWIND_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_BIT_REV_get")>
        Public Shared Function SOX_FILE_BIT_REV_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_NIB_REV_get")>
        Public Shared Function SOX_FILE_NIB_REV_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_ENDIAN_get")>
        Public Shared Function SOX_FILE_ENDIAN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_ENDBIG_get")>
        Public Shared Function SOX_FILE_ENDBIG_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_MONO_get")>
        Public Shared Function SOX_FILE_MONO_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_STEREO_get")>
        Public Shared Function SOX_FILE_STEREO_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_QUAD_get")>
        Public Shared Function SOX_FILE_QUAD_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_CHANS_get")>
        Public Shared Function SOX_FILE_CHANS_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_LIT_END_get")>
        Public Shared Function SOX_FILE_LIT_END_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_FILE_BIG_END_get")>
        Public Shared Function SOX_FILE_BIG_END_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_CHAN_get")>
        Public Shared Function SOX_EFF_CHAN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_RATE_get")>
        Public Shared Function SOX_EFF_RATE_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_PREC_get")>
        Public Shared Function SOX_EFF_PREC_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_LENGTH_get")>
        Public Shared Function SOX_EFF_LENGTH_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_MCHAN_get")>
        Public Shared Function SOX_EFF_MCHAN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_NULL_get")>
        Public Shared Function SOX_EFF_NULL_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_DEPRECATED_get")>
        Public Shared Function SOX_EFF_DEPRECATED_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_GAIN_get")>
        Public Shared Function SOX_EFF_GAIN_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_MODIFY_get")>
        Public Shared Function SOX_EFF_MODIFY_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_ALPHA_get")>
        Public Shared Function SOX_EFF_ALPHA_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_EFF_INTERNAL_get")>
        Public Shared Function SOX_EFF_INTERNAL_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_SOX_SEEK_SET_get")>
        Public Shared Function SOX_SEEK_SET_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_size_set")>
        Public Shared Sub sox_version_info_t_size_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_size_get")>
        Public Shared Function sox_version_info_t_size_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_flags_set")>
        Public Shared Sub sox_version_info_t_flags_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_flags_get")>
        Public Shared Function sox_version_info_t_flags_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_code_set")>
        Public Shared Sub sox_version_info_t_version_code_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_code_get")>
        Public Shared Function sox_version_info_t_version_code_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_set")>
        Public Shared Sub sox_version_info_t_version_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_get")>
        Public Shared Function sox_version_info_t_version_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_extra_set")>
        Public Shared Sub sox_version_info_t_version_extra_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_version_extra_get")>
        Public Shared Function sox_version_info_t_version_extra_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_time_set")>
        Public Shared Sub sox_version_info_t_time_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_time_get")>
        Public Shared Function sox_version_info_t_time_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_distro_set")>
        Public Shared Sub sox_version_info_t_distro_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_distro_get")>
        Public Shared Function sox_version_info_t_distro_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_compiler_set")>
        Public Shared Sub sox_version_info_t_compiler_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_compiler_get")>
        Public Shared Function sox_version_info_t_compiler_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_arch_set")>
        Public Shared Sub sox_version_info_t_arch_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info_t_arch_get")>
        Public Shared Function sox_version_info_t_arch_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_version_info_t")>
        Public Shared Function new_sox_version_info_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_version_info_t")>
        Public Shared Sub delete_sox_version_info_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_verbosity_set")>
        Public Shared Sub sox_globals_t_verbosity_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_verbosity_get")>
        Public Shared Function sox_globals_t_verbosity_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_output_message_handler_set")>
        Public Shared Sub sox_globals_t_output_message_handler_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_output_message_handler_get")>
        Public Shared Function sox_globals_t_output_message_handler_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_repeatable_set")>
        Public Shared Sub sox_globals_t_repeatable_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_repeatable_get")>
        Public Shared Function sox_globals_t_repeatable_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_bufsiz_set")>
        Public Shared Sub sox_globals_t_bufsiz_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_bufsiz_get")>
        Public Shared Function sox_globals_t_bufsiz_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_input_bufsiz_set")>
        Public Shared Sub sox_globals_t_input_bufsiz_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_input_bufsiz_get")>
        Public Shared Function sox_globals_t_input_bufsiz_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_ranqd1_set")>
        Public Shared Sub sox_globals_t_ranqd1_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_ranqd1_get")>
        Public Shared Function sox_globals_t_ranqd1_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_stdin_in_use_by_set")>
        Public Shared Sub sox_globals_t_stdin_in_use_by_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_stdin_in_use_by_get")>
        Public Shared Function sox_globals_t_stdin_in_use_by_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_stdout_in_use_by_set")>
        Public Shared Sub sox_globals_t_stdout_in_use_by_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_stdout_in_use_by_get")>
        Public Shared Function sox_globals_t_stdout_in_use_by_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_subsystem_set")>
        Public Shared Sub sox_globals_t_subsystem_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_subsystem_get")>
        Public Shared Function sox_globals_t_subsystem_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_tmp_path_set")>
        Public Shared Sub sox_globals_t_tmp_path_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_tmp_path_get")>
        Public Shared Function sox_globals_t_tmp_path_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_use_magic_set")>
        Public Shared Sub sox_globals_t_use_magic_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_use_magic_get")>
        Public Shared Function sox_globals_t_use_magic_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_use_threads_set")>
        Public Shared Sub sox_globals_t_use_threads_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_globals_t_use_threads_get")>
        Public Shared Function sox_globals_t_use_threads_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_globals_t")>
        Public Shared Function new_sox_globals_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_globals_t")>
        Public Shared Sub delete_sox_globals_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_rate_set")>
        Public Shared Sub sox_signalinfo_t_rate_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Double)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_rate_get")>
        Public Shared Function sox_signalinfo_t_rate_get(ByVal jarg1 As HandleRef) As Double
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_channels_set")>
        Public Shared Sub sox_signalinfo_t_channels_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_channels_get")>
        Public Shared Function sox_signalinfo_t_channels_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_precision_set")>
        Public Shared Sub sox_signalinfo_t_precision_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_precision_get")>
        Public Shared Function sox_signalinfo_t_precision_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_length_set")>
        Public Shared Sub sox_signalinfo_t_length_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_length_get")>
        Public Shared Function sox_signalinfo_t_length_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_mult_set")>
        Public Shared Sub sox_signalinfo_t_mult_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_signalinfo_t_mult_get")>
        Public Shared Function sox_signalinfo_t_mult_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_signalinfo_t")>
        Public Shared Function new_sox_signalinfo_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_signalinfo_t")>
        Public Shared Sub delete_sox_signalinfo_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_flags_set")>
        Public Shared Sub sox_encodings_info_t_flags_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_flags_get")>
        Public Shared Function sox_encodings_info_t_flags_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_name_set")>
        Public Shared Sub sox_encodings_info_t_name_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_name_get")>
        Public Shared Function sox_encodings_info_t_name_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_desc_set")>
        Public Shared Sub sox_encodings_info_t_desc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodings_info_t_desc_get")>
        Public Shared Function sox_encodings_info_t_desc_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_encodings_info_t")>
        Public Shared Function new_sox_encodings_info_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_encodings_info_t")>
        Public Shared Sub delete_sox_encodings_info_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_encoding_set")>
        Public Shared Sub sox_encodinginfo_t_encoding_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_encoding_get")>
        Public Shared Function sox_encodinginfo_t_encoding_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_bits_per_sample_set")>
        Public Shared Sub sox_encodinginfo_t_bits_per_sample_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_bits_per_sample_get")>
        Public Shared Function sox_encodinginfo_t_bits_per_sample_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_compression_set")>
        Public Shared Sub sox_encodinginfo_t_compression_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Double)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_compression_get")>
        Public Shared Function sox_encodinginfo_t_compression_get(ByVal jarg1 As HandleRef) As Double
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_bytes_set")>
        Public Shared Sub sox_encodinginfo_t_reverse_bytes_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_bytes_get")>
        Public Shared Function sox_encodinginfo_t_reverse_bytes_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_nibbles_set")>
        Public Shared Sub sox_encodinginfo_t_reverse_nibbles_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_nibbles_get")>
        Public Shared Function sox_encodinginfo_t_reverse_nibbles_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_bits_set")>
        Public Shared Sub sox_encodinginfo_t_reverse_bits_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_reverse_bits_get")>
        Public Shared Function sox_encodinginfo_t_reverse_bits_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_opposite_endian_set")>
        Public Shared Sub sox_encodinginfo_t_opposite_endian_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_encodinginfo_t_opposite_endian_get")>
        Public Shared Function sox_encodinginfo_t_opposite_endian_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_encodinginfo_t")>
        Public Shared Function new_sox_encodinginfo_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_encodinginfo_t")>
        Public Shared Sub delete_sox_encodinginfo_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_start_set")>
        Public Shared Sub sox_loopinfo_t_start_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_start_get")>
        Public Shared Function sox_loopinfo_t_start_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_length_set")>
        Public Shared Sub sox_loopinfo_t_length_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_length_get")>
        Public Shared Function sox_loopinfo_t_length_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_count_set")>
        Public Shared Sub sox_loopinfo_t_count_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_count_get")>
        Public Shared Function sox_loopinfo_t_count_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_type_set")>
        Public Shared Sub sox_loopinfo_t_type_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Byte)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_loopinfo_t_type_get")>
        Public Shared Function sox_loopinfo_t_type_get(ByVal jarg1 As HandleRef) As Byte
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_loopinfo_t")>
        Public Shared Function new_sox_loopinfo_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_loopinfo_t")>
        Public Shared Sub delete_sox_loopinfo_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDInote_set")>
        Public Shared Sub sox_instrinfo_t_MIDInote_set(ByVal jarg1 As HandleRef, ByVal jarg2 As SByte)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDInote_get")>
        Public Shared Function sox_instrinfo_t_MIDInote_get(ByVal jarg1 As HandleRef) As SByte
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDIlow_set")>
        Public Shared Sub sox_instrinfo_t_MIDIlow_set(ByVal jarg1 As HandleRef, ByVal jarg2 As SByte)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDIlow_get")>
        Public Shared Function sox_instrinfo_t_MIDIlow_get(ByVal jarg1 As HandleRef) As SByte
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDIhi_set")>
        Public Shared Sub sox_instrinfo_t_MIDIhi_set(ByVal jarg1 As HandleRef, ByVal jarg2 As SByte)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_MIDIhi_get")>
        Public Shared Function sox_instrinfo_t_MIDIhi_get(ByVal jarg1 As HandleRef) As SByte
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_loopmode_set")>
        Public Shared Sub sox_instrinfo_t_loopmode_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Byte)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_loopmode_get")>
        Public Shared Function sox_instrinfo_t_loopmode_get(ByVal jarg1 As HandleRef) As Byte
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_nloops_set")>
        Public Shared Sub sox_instrinfo_t_nloops_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_instrinfo_t_nloops_get")>
        Public Shared Function sox_instrinfo_t_nloops_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_instrinfo_t")>
        Public Shared Function new_sox_instrinfo_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_instrinfo_t")>
        Public Shared Sub delete_sox_instrinfo_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_buf_set")>
        Public Shared Sub sox_fileinfo_t_buf_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_buf_get")>
        Public Shared Function sox_fileinfo_t_buf_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_size_set")>
        Public Shared Sub sox_fileinfo_t_size_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_size_get")>
        Public Shared Function sox_fileinfo_t_size_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_count_set")>
        Public Shared Sub sox_fileinfo_t_count_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_count_get")>
        Public Shared Function sox_fileinfo_t_count_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_pos_set")>
        Public Shared Sub sox_fileinfo_t_pos_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_fileinfo_t_pos_get")>
        Public Shared Function sox_fileinfo_t_pos_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_fileinfo_t")>
        Public Shared Function new_sox_fileinfo_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_fileinfo_t")>
        Public Shared Sub delete_sox_fileinfo_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_sox_lib_version_code_set")>
        Public Shared Sub sox_format_handler_t_sox_lib_version_code_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_sox_lib_version_code_get")>
        Public Shared Function sox_format_handler_t_sox_lib_version_code_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_description_set")>
        Public Shared Sub sox_format_handler_t_description_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_description_get")>
        Public Shared Function sox_format_handler_t_description_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_names_set")>
        Public Shared Sub sox_format_handler_t_names_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_names_get")>
        Public Shared Function sox_format_handler_t_names_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_flags_set")>
        Public Shared Sub sox_format_handler_t_flags_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_flags_get")>
        Public Shared Function sox_format_handler_t_flags_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_startread_set")>
        Public Shared Sub sox_format_handler_t_startread_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_startread_get")>
        Public Shared Function sox_format_handler_t_startread_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_read_set")>
        Public Shared Sub sox_format_handler_t_read_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_read_get")>
        Public Shared Function sox_format_handler_t_read_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_stopread_set")>
        Public Shared Sub sox_format_handler_t_stopread_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_stopread_get")>
        Public Shared Function sox_format_handler_t_stopread_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_startwrite_set")>
        Public Shared Sub sox_format_handler_t_startwrite_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_startwrite_get")>
        Public Shared Function sox_format_handler_t_startwrite_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_set")>
        Public Shared Sub sox_format_handler_t_write_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_get")>
        Public Shared Function sox_format_handler_t_write_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_stopwrite_set")>
        Public Shared Sub sox_format_handler_t_stopwrite_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_stopwrite_get")>
        Public Shared Function sox_format_handler_t_stopwrite_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_seek_set")>
        Public Shared Sub sox_format_handler_t_seek_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_seek_get")>
        Public Shared Function sox_format_handler_t_seek_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_formats_set")>
        Public Shared Sub sox_format_handler_t_write_formats_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_formats_get")>
        Public Shared Function sox_format_handler_t_write_formats_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_rates_set")>
        Public Shared Sub sox_format_handler_t_write_rates_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_write_rates_get")>
        Public Shared Function sox_format_handler_t_write_rates_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_priv_size_set")>
        Public Shared Sub sox_format_handler_t_priv_size_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_handler_t_priv_size_get")>
        Public Shared Function sox_format_handler_t_priv_size_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_format_handler_t")>
        Public Shared Function new_sox_format_handler_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_format_handler_t")>
        Public Shared Sub delete_sox_format_handler_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_comments_set")>
        Public Shared Sub sox_oob_t_comments_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_comments_get")>
        Public Shared Function sox_oob_t_comments_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_instr_set")>
        Public Shared Sub sox_oob_t_instr_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_instr_get")>
        Public Shared Function sox_oob_t_instr_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_loops_set")>
        Public Shared Sub sox_oob_t_loops_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_oob_t_loops_get")>
        Public Shared Function sox_oob_t_loops_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_oob_t")>
        Public Shared Function new_sox_oob_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_oob_t")>
        Public Shared Sub delete_sox_oob_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_filename_set")>
        Public Shared Sub sox_format_t_filename_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_filename_get")>
        Public Shared Function sox_format_t_filename_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_signal_set")>
        Public Shared Sub sox_format_t_signal_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_signal_get")>
        Public Shared Function sox_format_t_signal_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_encoding_set")>
        Public Shared Sub sox_format_t_encoding_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_encoding_get")>
        Public Shared Function sox_format_t_encoding_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_filetype_set")>
        Public Shared Sub sox_format_t_filetype_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_filetype_get")>
        Public Shared Function sox_format_t_filetype_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_oob_set")>
        Public Shared Sub sox_format_t_oob_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_oob_get")>
        Public Shared Function sox_format_t_oob_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_seekable_set")>
        Public Shared Sub sox_format_t_seekable_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_seekable_get")>
        Public Shared Function sox_format_t_seekable_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_mode_set")>
        Public Shared Sub sox_format_t_mode_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Char)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_mode_get")>
        Public Shared Function sox_format_t_mode_get(ByVal jarg1 As HandleRef) As Char
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_olength_set")>
        Public Shared Sub sox_format_t_olength_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_olength_get")>
        Public Shared Function sox_format_t_olength_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_clips_set")>
        Public Shared Sub sox_format_t_clips_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_clips_get")>
        Public Shared Function sox_format_t_clips_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_sox_errno_set")>
        Public Shared Sub sox_format_t_sox_errno_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_sox_errno_get")>
        Public Shared Function sox_format_t_sox_errno_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_sox_errstr_set")>
        Public Shared Sub sox_format_t_sox_errstr_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_sox_errstr_get")>
        Public Shared Function sox_format_t_sox_errstr_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_fp_set")>
        Public Shared Sub sox_format_t_fp_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_fp_get")>
        Public Shared Function sox_format_t_fp_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_io_type_set")>
        Public Shared Sub sox_format_t_io_type_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_io_type_get")>
        Public Shared Function sox_format_t_io_type_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_tell_off_set")>
        Public Shared Sub sox_format_t_tell_off_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_tell_off_get")>
        Public Shared Function sox_format_t_tell_off_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_data_start_set")>
        Public Shared Sub sox_format_t_data_start_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_data_start_get")>
        Public Shared Function sox_format_t_data_start_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_handler_set")>
        Public Shared Sub sox_format_t_handler_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_handler_get")>
        Public Shared Function sox_format_t_handler_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_priv_set")>
        Public Shared Sub sox_format_t_priv_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_t_priv_get")>
        Public Shared Function sox_format_t_priv_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_format_t")>
        Public Shared Function new_sox_format_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_format_t")>
        Public Shared Sub delete_sox_format_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_tab_t_name_set")>
        Public Shared Sub sox_format_tab_t_name_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_tab_t_name_get")>
        Public Shared Function sox_format_tab_t_name_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_tab_t_fn_set")>
        Public Shared Sub sox_format_tab_t_fn_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_tab_t_fn_get")>
        Public Shared Function sox_format_tab_t_fn_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_format_tab_t")>
        Public Shared Function new_sox_format_tab_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_format_tab_t")>
        Public Shared Sub delete_sox_format_tab_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_globals_t_plot_set")>
        Public Shared Sub sox_effects_globals_t_plot_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_globals_t_plot_get")>
        Public Shared Function sox_effects_globals_t_plot_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_globals_t_global_info_set")>
        Public Shared Sub sox_effects_globals_t_global_info_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_globals_t_global_info_get")>
        Public Shared Function sox_effects_globals_t_global_info_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_effects_globals_t")>
        Public Shared Function new_sox_effects_globals_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_effects_globals_t")>
        Public Shared Sub delete_sox_effects_globals_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_name_set")>
        Public Shared Sub sox_effect_handler_t_name_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_name_get")>
        Public Shared Function sox_effect_handler_t_name_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_usage_set")>
        Public Shared Sub sox_effect_handler_t_usage_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_usage_get")>
        Public Shared Function sox_effect_handler_t_usage_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_flags_set")>
        Public Shared Sub sox_effect_handler_t_flags_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_flags_get")>
        Public Shared Function sox_effect_handler_t_flags_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_getopts_set")>
        Public Shared Sub sox_effect_handler_t_getopts_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_getopts_get")>
        Public Shared Function sox_effect_handler_t_getopts_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_start_set")>
        Public Shared Sub sox_effect_handler_t_start_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_start_get")>
        Public Shared Function sox_effect_handler_t_start_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_flow_set")>
        Public Shared Sub sox_effect_handler_t_flow_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_flow_get")>
        Public Shared Function sox_effect_handler_t_flow_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_drain_set")>
        Public Shared Sub sox_effect_handler_t_drain_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_drain_get")>
        Public Shared Function sox_effect_handler_t_drain_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_stop_set")>
        Public Shared Sub sox_effect_handler_t_stop_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_stop_get")>
        Public Shared Function sox_effect_handler_t_stop_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_kill_set")>
        Public Shared Sub sox_effect_handler_t_kill_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_kill_get")>
        Public Shared Function sox_effect_handler_t_kill_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_priv_size_set")>
        Public Shared Sub sox_effect_handler_t_priv_size_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_handler_t_priv_size_get")>
        Public Shared Function sox_effect_handler_t_priv_size_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_effect_handler_t")>
        Public Shared Function new_sox_effect_handler_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_effect_handler_t")>
        Public Shared Sub delete_sox_effect_handler_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_global_info_set")>
        Public Shared Sub sox_effect_t_global_info_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_global_info_get")>
        Public Shared Function sox_effect_t_global_info_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_in_signal_set")>
        Public Shared Sub sox_effect_t_in_signal_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_in_signal_get")>
        Public Shared Function sox_effect_t_in_signal_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_out_signal_set")>
        Public Shared Sub sox_effect_t_out_signal_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_out_signal_get")>
        Public Shared Function sox_effect_t_out_signal_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_in_encoding_set")>
        Public Shared Sub sox_effect_t_in_encoding_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_in_encoding_get")>
        Public Shared Function sox_effect_t_in_encoding_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_out_encoding_set")>
        Public Shared Sub sox_effect_t_out_encoding_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_out_encoding_get")>
        Public Shared Function sox_effect_t_out_encoding_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_handler_set")>
        Public Shared Sub sox_effect_t_handler_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_handler_get")>
        Public Shared Function sox_effect_t_handler_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_obuf_set")>
        Public Shared Sub sox_effect_t_obuf_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_obuf_get")>
        Public Shared Function sox_effect_t_obuf_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_obeg_set")>
        Public Shared Sub sox_effect_t_obeg_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_obeg_get")>
        Public Shared Function sox_effect_t_obeg_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_oend_set")>
        Public Shared Sub sox_effect_t_oend_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_oend_get")>
        Public Shared Function sox_effect_t_oend_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_imin_set")>
        Public Shared Sub sox_effect_t_imin_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_imin_get")>
        Public Shared Function sox_effect_t_imin_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_clips_set")>
        Public Shared Sub sox_effect_t_clips_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_clips_get")>
        Public Shared Function sox_effect_t_clips_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_flows_set")>
        Public Shared Sub sox_effect_t_flows_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_flows_get")>
        Public Shared Function sox_effect_t_flows_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_flow_set")>
        Public Shared Sub sox_effect_t_flow_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_flow_get")>
        Public Shared Function sox_effect_t_flow_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_priv_set")>
        Public Shared Sub sox_effect_t_priv_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_t_priv_get")>
        Public Shared Function sox_effect_t_priv_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_effect_t")>
        Public Shared Function new_sox_effect_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_effect_t")>
        Public Shared Sub delete_sox_effect_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_effects_set")>
        Public Shared Sub sox_effects_chain_t_effects_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_effects_get")>
        Public Shared Function sox_effects_chain_t_effects_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_table_size_set")>
        Public Shared Sub sox_effects_chain_t_table_size_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_table_size_get")>
        Public Shared Function sox_effects_chain_t_table_size_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_length_set")>
        Public Shared Sub sox_effects_chain_t_length_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_length_get")>
        Public Shared Function sox_effects_chain_t_length_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_ibufc_set")>
        Public Shared Sub sox_effects_chain_t_ibufc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_ibufc_get")>
        Public Shared Function sox_effects_chain_t_ibufc_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_obufc_set")>
        Public Shared Sub sox_effects_chain_t_obufc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_obufc_get")>
        Public Shared Function sox_effects_chain_t_obufc_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_global_info_set")>
        Public Shared Sub sox_effects_chain_t_global_info_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_global_info_get")>
        Public Shared Function sox_effects_chain_t_global_info_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_in_enc_set")>
        Public Shared Sub sox_effects_chain_t_in_enc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_in_enc_get")>
        Public Shared Function sox_effects_chain_t_in_enc_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_out_enc_set")>
        Public Shared Sub sox_effects_chain_t_out_enc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_chain_t_out_enc_get")>
        Public Shared Function sox_effects_chain_t_out_enc_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_sox_effects_chain_t")>
        Public Shared Function new_sox_effects_chain_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_sox_effects_chain_t")>
        Public Shared Sub delete_sox_effects_chain_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_version")>
        Public Shared Function sox_version() As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_version_info")>
        Public Shared Function sox_version_info() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_get_globals")>
        Public Shared Function sox_get_globals() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_get_encodings_info")>
        Public Shared Function sox_get_encodings_info() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_init_encodinginfo")>
        Public Shared Sub sox_init_encodinginfo(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_precision")>
        Public Shared Function sox_precision(ByVal jarg1 As Integer, ByVal jarg2 As UInteger) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_num_comments")>
        Public Shared Function sox_num_comments(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_append_comment")>
        Public Shared Sub sox_append_comment(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_append_comments")>
        Public Shared Sub sox_append_comments(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_copy_comments")>
        Public Shared Function sox_copy_comments(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_delete_comments")>
        Public Shared Sub sox_delete_comments(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_find_comment")>
        Public Shared Function sox_find_comment(ByVal jarg1 As HandleRef, ByVal jarg2 As String) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_init")>
        Public Shared Function sox_format_init() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_quit")>
        Public Shared Sub sox_format_quit()
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_init")>
        Public Shared Function sox_init() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_quit")>
        Public Shared Function sox_quit() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_get_format_fns")>
        Public Shared Function sox_get_format_fns() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_open_read")>
        Public Shared Function sox_open_read(ByVal jarg1 As String, ByVal jarg2 As HandleRef, ByVal jarg3 As HandleRef, ByVal jarg4 As String) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_open_mem_read")>
        Public Shared Function sox_open_mem_read(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger, ByVal jarg3 As HandleRef, ByVal jarg4 As HandleRef, ByVal jarg5 As String) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_format_supports_encoding")>
        Public Shared Function sox_format_supports_encoding(ByVal jarg1 As String, ByVal jarg2 As String, ByVal jarg3 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_write_handler")>
        Public Shared Function sox_write_handler(ByVal jarg1 As String, ByVal jarg2 As String, ByVal jarg3 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_open_write")>
        Public Shared Function sox_open_write(ByVal jarg1 As String, ByVal jarg2 As HandleRef, ByVal jarg3 As HandleRef, ByVal jarg4 As String, ByVal jarg5 As HandleRef, ByVal jarg6 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_open_mem_write")>
        Public Shared Function sox_open_mem_write(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger, ByVal jarg3 As HandleRef, ByVal jarg4 As HandleRef, ByVal jarg5 As String, ByVal jarg6 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_open_memstream_write")>
        Public Shared Function sox_open_memstream_write(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As HandleRef, ByVal jarg4 As HandleRef, ByVal jarg5 As String, ByVal jarg6 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_read")>
        Public Shared Function sox_read(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As UInteger) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_write")>
        Public Shared Function sox_write(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As UInteger) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_close")>
        Public Shared Function sox_close(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_seek")>
        Public Shared Function sox_seek(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger, ByVal jarg3 As Integer) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_find_format")>
        Public Shared Function sox_find_format(ByVal jarg1 As String, ByVal jarg2 As Integer) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_get_effects_globals")>
        Public Shared Function sox_get_effects_globals() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_find_effect")>
        Public Shared Function sox_find_effect(ByVal jarg1 As String) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_create_effect")>
        Public Shared Function sox_create_effect(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effect_options")>
        Public Shared Function sox_effect_options(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer, ByVal jarg3 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_get_effect_fns")>
        Public Shared Function sox_get_effect_fns() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_create_effects_chain")>
        Public Shared Function sox_create_effects_chain(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_delete_effects_chain")>
        Public Shared Sub sox_delete_effects_chain(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_add_effect")>
        Public Shared Function sox_add_effect(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As HandleRef, ByVal jarg4 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_flow_effects")>
        Public Shared Function sox_flow_effects(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_effects_clips")>
        Public Shared Function sox_effects_clips(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_stop_effect")>
        Public Shared Function sox_stop_effect(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_push_effect_last")>
        Public Shared Sub sox_push_effect_last(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_pop_effect_last")>
        Public Shared Function sox_pop_effect_last(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_delete_effect")>
        Public Shared Sub sox_delete_effect(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_delete_effect_last")>
        Public Shared Sub sox_delete_effect_last(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_delete_effects")>
        Public Shared Sub sox_delete_effects(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_trim_get_start")>
        Public Shared Function sox_trim_get_start(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_trim_clear_start")>
        Public Shared Sub sox_trim_clear_start(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_sox_is_playlist")>
        Public Shared Function sox_is_playlist(ByVal jarg1 As String) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_parse_playlist")>
        Public Shared Function sox_parse_playlist(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef, ByVal jarg3 As String) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_strerror")>
        Public Shared Function sox_strerror(ByVal jarg1 As Integer) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_sox_basename")>
        Public Shared Function sox_basename(ByVal jarg1 As String, ByVal jarg2 As UInteger, ByVal jarg3 As String) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_fail_impl")>
        Public Shared Sub lsx_fail_impl(ByVal jarg1 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_warn_impl")>
        Public Shared Sub lsx_warn_impl(ByVal jarg1 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_report_impl")>
        Public Shared Sub lsx_report_impl(ByVal jarg1 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_debug_impl")>
        Public Shared Sub lsx_debug_impl(ByVal jarg1 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_enum_item_text_set")>
        Public Shared Sub lsx_enum_item_text_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_enum_item_text_get")>
        Public Shared Function lsx_enum_item_text_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_enum_item_value_set")>
        Public Shared Sub lsx_enum_item_value_set(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_enum_item_value_get")>
        Public Shared Function lsx_enum_item_value_get(ByVal jarg1 As HandleRef) As UInteger
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_lsx_enum_item")>
        Public Shared Function new_lsx_enum_item() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_lsx_enum_item")>
        Public Shared Sub delete_lsx_enum_item(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_find_enum_item_none_get")>
        Public Shared Function lsx_find_enum_item_none_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_find_enum_item_case_sensitive_get")>
        Public Shared Function lsx_find_enum_item_case_sensitive_get() As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_find_enum_text")>
        Public Shared Function lsx_find_enum_text(ByVal jarg1 As String, ByVal jarg2 As HandleRef, ByVal jarg3 As Integer) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_find_enum_value")>
        Public Shared Function lsx_find_enum_value(ByVal jarg1 As UInteger, ByVal jarg2 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_enum_option")>
        Public Shared Function lsx_enum_option(ByVal jarg1 As Integer, ByVal jarg2 As String, ByVal jarg3 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_strends")>
        Public Shared Function lsx_strends(ByVal jarg1 As String, ByVal jarg2 As String) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_find_file_extension")>
        Public Shared Function lsx_find_file_extension(ByVal jarg1 As String) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_sigfigs3")>
        Public Shared Function lsx_sigfigs3(ByVal jarg1 As Double) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_sigfigs3p")>
        Public Shared Function lsx_sigfigs3p(ByVal jarg1 As Double) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_realloc")>
        Public Shared Function lsx_realloc(ByVal jarg1 As HandleRef, ByVal jarg2 As UInteger) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_strcasecmp")>
        Public Shared Function lsx_strcasecmp(ByVal jarg1 As String, ByVal jarg2 As String) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_strncasecmp")>
        Public Shared Function lsx_strncasecmp(ByVal jarg1 As String, ByVal jarg2 As String, ByVal jarg3 As UInteger) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_name_set")>
        Public Shared Sub lsx_option_t_name_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_name_get")>
        Public Shared Function lsx_option_t_name_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_has_arg_set")>
        Public Shared Sub lsx_option_t_has_arg_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_has_arg_get")>
        Public Shared Function lsx_option_t_has_arg_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_flag_set")>
        Public Shared Sub lsx_option_t_flag_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_flag_get")>
        Public Shared Function lsx_option_t_flag_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_val_set")>
        Public Shared Sub lsx_option_t_val_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_option_t_val_get")>
        Public Shared Function lsx_option_t_val_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_lsx_option_t")>
        Public Shared Function new_lsx_option_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_lsx_option_t")>
        Public Shared Sub delete_lsx_option_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_argc_set")>
        Public Shared Sub lsx_getopt_t_argc_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_argc_get")>
        Public Shared Function lsx_getopt_t_argc_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_argv_set")>
        Public Shared Sub lsx_getopt_t_argv_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_argv_get")>
        Public Shared Function lsx_getopt_t_argv_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_shortopts_set")>
        Public Shared Sub lsx_getopt_t_shortopts_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_shortopts_get")>
        Public Shared Function lsx_getopt_t_shortopts_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_longopts_set")>
        Public Shared Sub lsx_getopt_t_longopts_set(ByVal jarg1 As HandleRef, ByVal jarg2 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_longopts_get")>
        Public Shared Function lsx_getopt_t_longopts_get(ByVal jarg1 As HandleRef) As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_flags_set")>
        Public Shared Sub lsx_getopt_t_flags_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_flags_get")>
        Public Shared Function lsx_getopt_t_flags_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_curpos_set")>
        Public Shared Sub lsx_getopt_t_curpos_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_curpos_get")>
        Public Shared Function lsx_getopt_t_curpos_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_ind_set")>
        Public Shared Sub lsx_getopt_t_ind_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_ind_get")>
        Public Shared Function lsx_getopt_t_ind_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_opt_set")>
        Public Shared Sub lsx_getopt_t_opt_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_opt_get")>
        Public Shared Function lsx_getopt_t_opt_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_arg_set")>
        Public Shared Sub lsx_getopt_t_arg_set(ByVal jarg1 As HandleRef, ByVal jarg2 As String)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_arg_get")>
        Public Shared Function lsx_getopt_t_arg_get(ByVal jarg1 As HandleRef) As String
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_lngind_set")>
        Public Shared Sub lsx_getopt_t_lngind_set(ByVal jarg1 As HandleRef, ByVal jarg2 As Integer)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_t_lngind_get")>
        Public Shared Function lsx_getopt_t_lngind_get(ByVal jarg1 As HandleRef) As Integer
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_new_lsx_getopt_t")>
        Public Shared Function new_lsx_getopt_t() As IntPtr
        End Function

        <DllImport("libsox", EntryPoint:="CSharp_delete_lsx_getopt_t")>
        Public Shared Sub delete_lsx_getopt_t(ByVal jarg1 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt_init")>
        Public Shared Sub lsx_getopt_init(ByVal jarg1 As Integer, ByVal jarg2 As HandleRef, ByVal jarg3 As String, ByVal jarg4 As HandleRef, ByVal jarg5 As Integer, ByVal jarg6 As Integer, ByVal jarg7 As HandleRef)
        End Sub

        <DllImport("libsox", EntryPoint:="CSharp_lsx_getopt")>
        Public Shared Function lsx_getopt(ByVal jarg1 As HandleRef) As Integer
        End Function
    End Class

End Namespace
