Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class lsx_getopt_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As lsx_getopt_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_lsx_getopt_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property argc() As Integer
            Set(ByVal value As Integer)
                libsoxPINVOKE.lsx_getopt_t_argc_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Integer = libsoxPINVOKE.lsx_getopt_t_argc_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property argv() As SWIGTYPE_p_p_char
            Set(ByVal value As SWIGTYPE_p_p_char)
                libsoxPINVOKE.lsx_getopt_t_argv_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.lsx_getopt_t_argv_get(swigCPtr)
                Dim ret As SWIGTYPE_p_p_char = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_p_char(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property shortopts() As String
            Set(ByVal value As String)
                libsoxPINVOKE.lsx_getopt_t_shortopts_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.lsx_getopt_t_shortopts_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property longopts() As lsx_option_t
            Set(ByVal value As lsx_option_t)
                libsoxPINVOKE.lsx_getopt_t_longopts_set(swigCPtr, lsx_option_t.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.lsx_getopt_t_longopts_get(swigCPtr)
                Dim ret As lsx_option_t = If(cPtr = IntPtr.Zero, Nothing, New lsx_option_t(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property flags() As lsx_getopt_flags_t
            Set(ByVal value As lsx_getopt_flags_t)
                libsoxPINVOKE.lsx_getopt_t_flags_set(swigCPtr, CInt(value))
            End Set
            Get
                Dim ret As lsx_getopt_flags_t = CType(libsoxPINVOKE.lsx_getopt_t_flags_get(swigCPtr), lsx_getopt_flags_t)
                Return ret
            End Get
        End Property

        Public Property curpos() As String
            Set(ByVal value As String)
                libsoxPINVOKE.lsx_getopt_t_curpos_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.lsx_getopt_t_curpos_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property ind() As Integer
            Set(ByVal value As Integer)
                libsoxPINVOKE.lsx_getopt_t_ind_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Integer = libsoxPINVOKE.lsx_getopt_t_ind_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property opt() As Integer
            Set(ByVal value As Integer)
                libsoxPINVOKE.lsx_getopt_t_opt_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Integer = libsoxPINVOKE.lsx_getopt_t_opt_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property arg() As String
            Set(ByVal value As String)
                libsoxPINVOKE.lsx_getopt_t_arg_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.lsx_getopt_t_arg_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property lngind() As Integer
            Set(ByVal value As Integer)
                libsoxPINVOKE.lsx_getopt_t_lngind_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Integer = libsoxPINVOKE.lsx_getopt_t_lngind_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_lsx_getopt_t(), True)
        End Sub

    End Class

End Namespace
