' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum lsx_option_arg_t
        lsx_option_arg_none
        lsx_option_arg_required
        lsx_option_arg_optional
    End Enum

End Namespace
