' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum lsx_getopt_flags_t
        lsx_getopt_flag_none = 0
        lsx_getopt_flag_opterr = 1
        lsx_getopt_flag_longonly = 2
    End Enum

End Namespace
