' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_encodings_flags_t
        sox_encodings_none = 0
        sox_encodings_lossy1 = 1
        sox_encodings_lossy2 = 2
    End Enum

End Namespace
