Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class sox_globals_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As sox_globals_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_sox_globals_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property verbosity() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_globals_t_verbosity_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_globals_t_verbosity_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property output_message_handler() As SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_q_const__char_va_list__void
            Set(ByVal value As SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_q_const__char_va_list__void)
                libsoxPINVOKE.sox_globals_t_output_message_handler_set(swigCPtr, SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_q_const__char_va_list__void.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_globals_t_output_message_handler_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_q_const__char_va_list__void = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_q_const__char_va_list__void(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property repeatable() As sox_bool
            Set(ByVal value As sox_bool)
                libsoxPINVOKE.sox_globals_t_repeatable_set(swigCPtr, CInt(value))
            End Set
            Get
                Dim ret As sox_bool = CType(libsoxPINVOKE.sox_globals_t_repeatable_get(swigCPtr), sox_bool)
                Return ret
            End Get
        End Property

        Public Property bufsiz() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_globals_t_bufsiz_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_globals_t_bufsiz_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property input_bufsiz() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_globals_t_input_bufsiz_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_globals_t_input_bufsiz_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property ranqd1() As Integer
            Set(ByVal value As Integer)
                libsoxPINVOKE.sox_globals_t_ranqd1_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Integer = libsoxPINVOKE.sox_globals_t_ranqd1_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property stdin_in_use_by() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_globals_t_stdin_in_use_by_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_globals_t_stdin_in_use_by_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property stdout_in_use_by() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_globals_t_stdout_in_use_by_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_globals_t_stdout_in_use_by_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property subsystem() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_globals_t_subsystem_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_globals_t_subsystem_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property tmp_path() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_globals_t_tmp_path_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_globals_t_tmp_path_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property use_magic() As sox_bool
            Set(ByVal value As sox_bool)
                libsoxPINVOKE.sox_globals_t_use_magic_set(swigCPtr, CInt(value))
            End Set
            Get
                Dim ret As sox_bool = CType(libsoxPINVOKE.sox_globals_t_use_magic_get(swigCPtr), sox_bool)
                Return ret
            End Get
        End Property

        Public Property use_threads() As sox_bool
            Set(ByVal value As sox_bool)
                libsoxPINVOKE.sox_globals_t_use_threads_set(swigCPtr, CInt(value))
            End Set
            Get
                Dim ret As sox_bool = CType(libsoxPINVOKE.sox_globals_t_use_threads_get(swigCPtr), sox_bool)
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_sox_globals_t(), True)
        End Sub

    End Class

End Namespace
