Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class sox_effect_handler_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As sox_effect_handler_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_sox_effect_handler_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property name() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_effect_handler_t_name_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_effect_handler_t_name_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property usage() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_effect_handler_t_usage_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_effect_handler_t_usage_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property flags() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_effect_handler_t_flags_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_effect_handler_t_flags_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property getopts() As SWIGTYPE_p_f_p_struct_sox_effect_t_int_a___p_char__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t_int_a___p_char__int)
                libsoxPINVOKE.sox_effect_handler_t_getopts_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t_int_a___p_char__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_getopts_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t_int_a___p_char__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t_int_a___p_char__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property start() As SWIGTYPE_p_f_p_struct_sox_effect_t__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t__int)
                libsoxPINVOKE.sox_effect_handler_t_start_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_start_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property flow() As SWIGTYPE_p_f_p_struct_sox_effect_t_p_q_const__int_p_int_p_size_t_p_size_t__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t_p_q_const__int_p_int_p_size_t_p_size_t__int)
                libsoxPINVOKE.sox_effect_handler_t_flow_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t_p_q_const__int_p_int_p_size_t_p_size_t__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_flow_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t_p_q_const__int_p_int_p_size_t_p_size_t__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t_p_q_const__int_p_int_p_size_t_p_size_t__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property drain() As SWIGTYPE_p_f_p_struct_sox_effect_t_p_int_p_size_t__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t_p_int_p_size_t__int)
                libsoxPINVOKE.sox_effect_handler_t_drain_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t_p_int_p_size_t__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_drain_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t_p_int_p_size_t__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t_p_int_p_size_t__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property [stop]() As SWIGTYPE_p_f_p_struct_sox_effect_t__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t__int)
                libsoxPINVOKE.sox_effect_handler_t_stop_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_stop_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property kill() As SWIGTYPE_p_f_p_struct_sox_effect_t__int
            Set(ByVal value As SWIGTYPE_p_f_p_struct_sox_effect_t__int)
                libsoxPINVOKE.sox_effect_handler_t_kill_set(swigCPtr, SWIGTYPE_p_f_p_struct_sox_effect_t__int.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_effect_handler_t_kill_get(swigCPtr)
                Dim ret As SWIGTYPE_p_f_p_struct_sox_effect_t__int = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_f_p_struct_sox_effect_t__int(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property priv_size() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_effect_handler_t_priv_size_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_effect_handler_t_priv_size_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_sox_effect_handler_t(), True)
        End Sub

    End Class

End Namespace
