' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_loop_flags_t
        sox_loop_none = 0
        sox_loop_forward = 1
        sox_loop_forward_back = 2
        sox_loop_8 = 32
        sox_loop_sustain_decay = 64
    End Enum

End Namespace
