Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class sox_version_info_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As sox_version_info_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_sox_version_info_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property size() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_version_info_t_size_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_version_info_t_size_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property flags() As sox_version_flags_t
            Set(ByVal value As sox_version_flags_t)
                libsoxPINVOKE.sox_version_info_t_flags_set(swigCPtr, CInt(value))
            End Set
            Get
                Dim ret As sox_version_flags_t = CType(libsoxPINVOKE.sox_version_info_t_flags_get(swigCPtr), sox_version_flags_t)
                Return ret
            End Get
        End Property

        Public Property version_code() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_version_info_t_version_code_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_version_info_t_version_code_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property version() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_version_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_version_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property version_extra() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_version_extra_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_version_extra_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property time() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_time_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_time_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property distro() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_distro_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_distro_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property compiler() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_compiler_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_compiler_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property arch() As String
            Set(ByVal value As String)
                libsoxPINVOKE.sox_version_info_t_arch_set(swigCPtr, value)
            End Set
            Get
                Dim ret As String = libsoxPINVOKE.sox_version_info_t_arch_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_sox_version_info_t(), True)
        End Sub

    End Class

End Namespace
