Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class sox_oob_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As sox_oob_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_sox_oob_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property comments() As SWIGTYPE_p_p_char
            Set(ByVal value As SWIGTYPE_p_p_char)
                libsoxPINVOKE.sox_oob_t_comments_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_oob_t_comments_get(swigCPtr)
                Dim ret As SWIGTYPE_p_p_char = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_p_char(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property instr() As sox_instrinfo_t
            Set(ByVal value As sox_instrinfo_t)
                libsoxPINVOKE.sox_oob_t_instr_set(swigCPtr, sox_instrinfo_t.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_oob_t_instr_get(swigCPtr)
                Dim ret As sox_instrinfo_t = If(cPtr = IntPtr.Zero, Nothing, New sox_instrinfo_t(cPtr, False))
                Return ret
            End Get
        End Property

        Public Property loops() As sox_loopinfo_t
            Set(ByVal value As sox_loopinfo_t)
                libsoxPINVOKE.sox_oob_t_loops_set(swigCPtr, sox_loopinfo_t.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_oob_t_loops_get(swigCPtr)
                Dim ret As sox_loopinfo_t = If(cPtr = IntPtr.Zero, Nothing, New sox_loopinfo_t(cPtr, False))
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_sox_oob_t(), True)
        End Sub

    End Class

End Namespace
