' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_version_flags_t
        sox_version_none = 0
        sox_version_have_popen = 1
        sox_version_have_magic = 2
        sox_version_have_threads = 4
        sox_version_have_memopen = 8
    End Enum

End Namespace
