' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_encoding_t
        SOX_ENCODING_UNKNOWN
        SOX_ENCODING_SIGN2
        SOX_ENCODING_UNSIGNED
        SOX_ENCODING_FLOAT
        SOX_ENCODING_FLOAT_TEXT
        SOX_ENCODING_FLAC
        SOX_ENCODING_HCOM
        SOX_ENCODING_WAVPACK
        SOX_ENCODING_WAVPACKF
        SOX_ENCODING_ULAW
        SOX_ENCODING_ALAW
        SOX_ENCODING_G721
        SOX_ENCODING_G723
        SOX_ENCODING_CL_ADPCM
        SOX_ENCODING_CL_ADPCM16
        SOX_ENCODING_MS_ADPCM
        SOX_ENCODING_IMA_ADPCM
        SOX_ENCODING_OKI_ADPCM
        SOX_ENCODING_DPCM
        SOX_ENCODING_DWVW
        SOX_ENCODING_DWVWN
        SOX_ENCODING_GSM
        SOX_ENCODING_MP3
        SOX_ENCODING_VORBIS
        SOX_ENCODING_AMR_WB
        SOX_ENCODING_AMR_NB
        SOX_ENCODING_CVSD
        SOX_ENCODING_LPC10
        SOX_ENCODINGS
    End Enum

End Namespace
