' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_plot_t
        sox_plot_off
        sox_plot_octave
        sox_plot_gnuplot
        sox_plot_data
    End Enum

End Namespace
