Imports System.Runtime.InteropServices

' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig


    Public Class sox_signalinfo_t
        Implements IDisposable
        Private swigCPtr As HandleRef
        Protected swigCMemOwn As Boolean

        Friend Sub New(ByVal cPtr As IntPtr, ByVal cMemoryOwn As Boolean)
            swigCMemOwn = cMemoryOwn
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Friend Shared Function getCPtr(ByVal obj As sox_signalinfo_t) As HandleRef
            Return If(obj Is Nothing, New HandleRef(Nothing, IntPtr.Zero), obj.swigCPtr)
        End Function

        Protected Overrides Sub Finalize()
            Dispose()
        End Sub

        Public Overridable Sub Dispose() Implements IDisposable.Dispose
            SyncLock Me
                If swigCPtr.Handle <> IntPtr.Zero Then
                    If swigCMemOwn Then
                        swigCMemOwn = False
                        libsoxPINVOKE.delete_sox_signalinfo_t(swigCPtr)
                    End If
                    swigCPtr = New HandleRef(Nothing, IntPtr.Zero)
                End If
                GC.SuppressFinalize(Me)
            End SyncLock
        End Sub

        Public Sub New(ByVal cPtr As IntPtr)
            swigCMemOwn = False
            swigCPtr = New HandleRef(Me, cPtr)
        End Sub

        Public Function GetswigCPtr() As IntPtr
            Return swigCPtr.Handle
        End Function


        Public Property rate() As Double
            Set(ByVal value As Double)
                libsoxPINVOKE.sox_signalinfo_t_rate_set(swigCPtr, value)
            End Set
            Get
                Dim ret As Double = libsoxPINVOKE.sox_signalinfo_t_rate_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property channels() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_signalinfo_t_channels_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_signalinfo_t_channels_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property precision() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_signalinfo_t_precision_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_signalinfo_t_precision_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property length() As UInteger
            Set(ByVal value As UInteger)
                libsoxPINVOKE.sox_signalinfo_t_length_set(swigCPtr, value)
            End Set
            Get
                Dim ret As UInteger = libsoxPINVOKE.sox_signalinfo_t_length_get(swigCPtr)
                Return ret
            End Get
        End Property

        Public Property mult() As SWIGTYPE_p_double
            Set(ByVal value As SWIGTYPE_p_double)
                libsoxPINVOKE.sox_signalinfo_t_mult_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value))
            End Set
            Get
                Dim cPtr As IntPtr = libsoxPINVOKE.sox_signalinfo_t_mult_get(swigCPtr)
                Dim ret As SWIGTYPE_p_double = If(cPtr = IntPtr.Zero, Nothing, New SWIGTYPE_p_double(cPtr, False))
                Return ret
            End Get
        End Property

        Public Sub New()
            Me.New(libsoxPINVOKE.new_sox_signalinfo_t(), True)
        End Sub

    End Class

End Namespace
