' ----------------------------------------------------------------------------
' * This file was automatically generated by SWIG (http://www.swig.org).
' * Version 2.0.10
' *
' * Do not make changes to this file unless you know what you are doing--modify
' * the SWIG interface file instead.
' * ----------------------------------------------------------------------------- 

Namespace swig

    Public Enum sox_error_t
        SOX_SUCCESS = 0
        SOX_EOF = -1
        SOX_EHDR = 2000
        SOX_EFMT
        SOX_ENOMEM
        SOX_EPERM
        SOX_ENOTSUP
        SOX_EINVAL
    End Enum

End Namespace
